manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: nxtkb
      url-base: https://github.com/nxtkb
  projects:
    - name: zmk
      remote: nxtkb
      revision: 5fb1f293caeffce2eb1637e03905ae1336b9e291
      import: app/west.yml
    - name: zmk-feature-codex-micro
      remote: nxtkb
      revision: 077cc618ac3beb9acb92f86ee067d676ed9629f9
    - name: zmk-behavior-report
      remote: nxtkb
      revision: 476f43da1f98b4a6150c9c0e499a257bd64a29a0
      import: west.yml
  self:
    path: config
